ALTER TABLE NAZNACH DROP CONSTRAINT FK_NAZNACH_ID_PRIEM
ALTER TABLE OPLATA DROP CONSTRAINT FK_OPLATA_ID_NAZNACH
ALTER TABLE PDATA DROP CONSTRAINT FK_PDATA_PID
ALTER TABLE PRIEM DROP CONSTRAINT FK_PRIEM_PID
DROP TABLE NAZNACH
DROP TABLE OPLATA
DROP TABLE PDATA
DROP TABLE PERSON
DROP TABLE PRIEM
